### ISSUE TITLE
java.lang.RuntimeException: An unvisited state has non-empty transitions.

### ISSUE THREAD

**Issue by tianxiaogu** [tianxiaogu/ape#5]
java.lang.RuntimeException: An unvisited state has non-empty transitions.
        at com.android.commands.monkey.ape.agent.StatefulAgent.checkAndRefreshNewState(StatefulAgent.java:525)
        at com.android.commands.monkey.ape.agent.StatefulAgent.preCheckTrivialNewState(StatefulAgent.java:565)
        at com.android.commands.monkey.ape.agent.StatefulAgent.buildAndValidateNewState(StatefulAgent.java:574)
        at com.android.commands.monkey.ape.agent.StatefulAgent.updateStateInternal(StatefulAgent.java:586)
        at com.android.commands.monkey.ape.agent.ApeAgent.updateStateWrapper(ApeAgent.java:264)
        at com.android.commands.monkey.ape.agent.ApeAgent.updateState(ApeAgent.java:251)
        at com.android.commands.monkey.MonkeySourceApe.generateEvents(MonkeySourceApe.java:782)
        at com.android.commands.monkey.MonkeySourceApe.getNextEvent(MonkeySourceApe.java:1277)
        at com.android.commands.monkey.Monkey.runMonkeyCycles(Monkey.java:1377)
        at com.android.commands.monkey.Monkey.run(Monkey.java:770)
        at com.android.commands.monkey.Monkey.main(Monkey.java:612)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

_Originally posted by @sdhuie in https://github.com/tianxiaogu/ape/issues/4#issuecomment-663826272_

**Comment by tianxiaogu** [comment]
Recent changes to StateNamingManager and Naming have broken the Model evolution part.
