### ISSUE TITLE
Facing Illegal State Exception 

### ISSUE THREAD

**Issue by safwatalikhan** [tianxiaogu/ape#8]
Run cmd: adb shell CLASSPATH=/data/local/tmp/ape.jar /system/bin/app_process /data/local/tmp/ com.android.commands.monkey.Monkey -p com.contextlogic.wish --running-minutes 2 --ape sata
[APE] Rename /sdcard/sata-com.contextlogic.wish-ape-sata-running-minutes-2 to /sdcard/sata-com.contextlogic.wish-ape-sata-running-minutes-2.2
[APE] *** INFO *** InputMethod ID: com.android.inputmethod.latin/.LatinIME
[APE] Power Manager says we are interactive
[APE] Internal error
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@acd9443already registered!
        at android.os.Parcel.readException(Parcel.java:1607)
        at android.os.Parcel.readException(Parcel.java:1552)
        at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:352)
        at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:337)
        at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:89)
        at android.app.UiAutomation.connect(UiAutomation.java:197)
        at com.android.commands.monkey.MonkeySourceApe.connect(MonkeySourceApe.java:161)
        at com.android.commands.monkey.MonkeySourceApe.<init>(MonkeySourceApe.java:231)
        at com.android.commands.monkey.Monkey.run(Monkey.java:721)
        at com.android.commands.monkey.Monkey.main(Monkey.java:607)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
[APE] Please report this bug to developers.

**Comment by tianxiaogu** [comment]
Hi @safwatalikhan , thank you very much for reporting the issue. This issue may be because there is another testing tool (e.g., a zombie Ape process) running in your Android device and occupying the accessibility service. You may check if there is any suspicious process running in the background.
